markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - abbr
  - pymdownx.snippets

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

extra_css:
  - stylesheets/extra.css

plugins:
  - social:
      cards_layout: default/only/image
      cards_layout_options:
        background_image: docs/assets/images/background.jpg

site_name: 'Ruan Mei Mains ❀ Honkai: Star Rail'
site_url: https://ruanmeimains.com/

nav:
  - Home: 'index.md'
  - Ruan Mei Guides:
    - 'Ruan Mei Quick Guide': 'ruanmei-guides/quick.md'
    - 'Ruan Mei Full Guide': 'ruanmei-guides/full.md'
  - Ruan Mei Lore: 'lore.md'
  - Socials:
    - 'Discord': 'https://discord.gg/ruanmei" target="_blank'
    - 'Reddit': 'https://www.reddit.com/r/RuanMeiMains/" target="_blank'
    - 'Twitter': 'https://twitter.com/ruanmeidaily__" target="_blank'
  - Join our Team: 'applications.md'

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: teal
  favicon: assets/flower.png
  logo: assets/white_girl_save_me.png
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - search.highlight
    - search.suggest
    - search.share
    - announce.dismiss
    - navigation.footer
    - navigation.top
    - content.tooltips
  icon:
    admonition:
      tip: octicons/question-16
    annotation: material/help-circle

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/ruanmei" target="_blank
    - icon: fontawesome/brands/reddit
      link: https://reddit.com/r/RuanMeiMains" target="_blank
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ruanmeidaily__" target="_blank
